# Uncomment this line to define a global platform for your project
workspace 'KMSClient.xcworkspace'
platform :ios, '8.0'
use_frameworks!

def shared_pods
   pod 'SocketRocket', '0.5.1'
   pod 'ReactiveObjC', '3.0.0'
   pod 'MantleNullValuesOmit', '0.0.2'
   pod 'Mantle', '2.1.0'
end

target :LoopBackCall do
   project 'Sample/LoopBackCall/LoopBackCall.xcodeproj'
   pod 'WebRTC', '61.5.19063'
   shared_pods
  end

target 'KMSClient' do
  project 'KMSClient.xcodeproj'
  shared_pods
end

