# Uncomment this line to define a global platform for your project
workspace 'KMSClient.xcworkspace'
platform :ios, '8.0'
use_frameworks!


def shared_pods
   pod 'ReactiveObjC', '2.1.2'
   pod 'MantleNullValuesOmit', '0.0.2'
   pod 'NSDictionaryMerge', '1.0'
   pod 'Mantle', '2.1.0'

end

target :LoopBackCall do
   project 'Sample/LoopBackCall/LoopBackCall.xcodeproj'
   pod 'WebRTC', '57.2.16123'
   shared_pods
  end

target 'KMSClient' do
  project 'KMSClient.xcodeproj'
  pod 'SocketRocket', '0.5.1'
  shared_pods
end

